name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake gcc make
      - name: Generate configure script
        run: |
          autoconf -o ./configure Makefile.ac
          ls -l configure  # Verify configure script is created
          chmod +x configure
      - name: Configure
        run: ./configure
      - name: Make
        run: make

